language: go

go:
  - 1.4

install:
  - export PATH=$GOPATH/bin:./_tools/etcd/bin:$PATH
  - make install-travis

deploy:
  provider: releases
  api_key: "cbe3d1bd50aad176ab692943194a95d48e55426d"
  file: 
    - "_output/local/bin/linux/amd64/oc"
    - "_output/local/bin/linux/amd64/openshift"
  skip_cleanup: true
    
sudo: false
