language: go

go:
  - 1.4

install:
  - export PATH=$GOPATH/bin:./_tools/etcd/bin:$PATH
  - make install-travis

deploy:
  provider: releases
  api_key: "8d482fd9d552ae7414175b26dad5ccb3d9dc1177"
  file: 
    - "_output/local/bin/linux/amd64/oc"
    - "_output/local/bin/linux/amd64/openshift"
  skip_cleanup: true
    
sudo: false
